#!/usr/bin/env bash
# Script that displays information about subdomains

#!/bin/bash

# Bash function to query and display subdomain information
query_subdomain() {
    local domain=$1
    local subdomain=$2
    local output=$(dig "$subdomain.$domain" | awk '/IN/{print $4, $5}')
    local record_type=$(echo "$output" | awk '{print $1}')
    local destination=$(echo "$output" | awk '{print $2}')

    echo "The subdomain $subdomain is a $record_type record and points to $destination"
}

# Main script logic
domain=$1
subdomain=$2

if [ -z "$domain" ]; then
    echo "Error: Domain name is mandatory."
    exit 1
fi

if [ -z "$subdomain" ]; then
    # Query and display information for the default subdomains
    for subdomain in www lb-01 web-01 web-02; do
        query_subdomain "$domain" "$subdomain"
    done
else
    # Query and display information for the specified subdomain
    query_subdomain "$domain" "$subdomain"
fi

