#!/usr/bin/env bash
# prints infinity and beyond
# prints I am invisible when SIGTERM recived

while true
do
  echo "To infinity and beyond"
  sleep 2
  trap 'echo "I am invincible!!!"' SIGTERM 
done
