#!/usr/bin/env bash
# This prints "Best School" using a while loop
# When on 10th iteration, prints "Hi" then ends with "Best school"

x=0

while [ $x -lt 10 ]
do
  if [ $x -eq 9 ]
  then
    echo "Hi"
  fi
  echo "Best School"
  (( x++ ))
done

