#!/usr/bin/env bash
# This changes hostname in an Ubuntu server
# 127.0.0.2 would replace localhost
# 8.8.8.8 would change facebook.com

cp /etc/hosts ~/hosts.new
echo "127.0.0.2		localhost" > ~/hosts.new
echo "8.8.8.8		facebook.com" >> ~/hosts.new
cp -f ~/hosts.new /etc/hosts
